### ISSUE TITLE
For C++ hackkerank Problem and solution 

### ISSUE THREAD

**Issue by Shikha785** [Riddhi9570/Riddhi9570#1]
Please allow me to create a new folder for c++ hackkerank problem and solution.

**Comment by Riddhi9570** [comment]
I guess you have created an issue in this repository by mistake😅. No problem😇. If you want to contribute, please create an issue in this repository - [HackerrankPracticeProblems](https://github.com/Riddhi9570/HackerrankPracticeProblems).
